Integrate changes to kubernetes/cluster/get-kube.sh into get-kube-secure.sh

diff --git a/k8s.io/configmap-www-get.yaml b/k8s.io/configmap-www-get.yaml
--- a/k8s.io/configmap-www-get.yaml
+++ b/k8s.io/configmap-www-get.yaml
@@ -4,10 +4,11 @@ metadata:
   name: www-get
 data:
   # Adding new entries here will make them appear as files in the deployment.
+  # TODO: is there a better way to keep this up-to-date with cluster/get-kube.sh in kubernetes/kubernetes?
   get-kube-secure.sh: |
     #!/bin/bash
 
-    # Copyright 2014 The Kubernetes Authors All rights reserved.
+    # Copyright 2014 The Kubernetes Authors.
     #
     # Licensed under the Apache License, Version 2.0 (the "License");
     # you may not use this file except in compliance with the License.
@@ -35,22 +36,58 @@ data:
     #   * export KUBERNETES_PROVIDER=gke; wget -q -O - https://get.k8s.io | bash
     #  Amazon EC2
     #   * export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
+    #  Libvirt (with CoreOS as a guest operating system)
+    #   * export KUBERNETES_PROVIDER=libvirt-coreos; wget -q -O - https://get.k8s.io | bash
     #  Microsoft Azure
-    #   * export KUBERNETES_PROVIDER=azure; wget -q -O - https://get.k8s.io | bash
+    #   * export KUBERNETES_PROVIDER=azure-legacy; wget -q -O - https://get.k8s.io | bash
     #  Vagrant (local virtual machines)
     #   * export KUBERNETES_PROVIDER=vagrant; wget -q -O - https://get.k8s.io | bash
     #  VMWare VSphere
     #   * export KUBERNETES_PROVIDER=vsphere; wget -q -O - https://get.k8s.io | bash
+    #  VMWare Photon Controller
+    #   * export KUBERNETES_PROVIDER=photon-controller; wget -q -O - https://get.k8s.io | bash
     #  Rackspace
     #   * export KUBERNETES_PROVIDER=rackspace; wget -q -O - https://get.k8s.io | bash
+    #  OpenStack-Heat
+    #   * export KUBERNETES_PROVIDER=openstack-heat; wget -q -O - https://get.k8s.io | bash
     #
-    #  Set KUBERNETES_SKIP_DOWNLOAD to non-empty to skip downloading a release.
+    #  Set KUBERNETES_RELEASE to choose a specific release instead of the current
+    #    stable release, (e.g. 'v1.3.7').
+    #    See https://github.com/kubernetes/kubernetes/releases for release options.
+    #  Set KUBERNETES_RELEASE_URL to choose where to download binaries from.
+    #    (Defaults to https://storage.googleapis.com/kubernetes-release/release).
+    #
+    #  Set KUBERNETES_SERVER_ARCH to choose the server (Kubernetes cluster)
+    #  architecture to download:
+    #    * amd64 [default]
+    #    * arm
+    #    * arm64
+    #
+    #  Set KUBERNETES_SKIP_DOWNLOAD to skip downloading a release.
     #  Set KUBERNETES_SKIP_CONFIRM to skip the installation confirmation prompt.
+    #  Set KUBERNETES_SKIP_CREATE_CLUSTER to skip starting a cluster.
+
     set -o errexit
     set -o nounset
     set -o pipefail
 
+    KUBERNETES_RELEASE_URL="${KUBERNETES_RELEASE_URL:-https://storage.googleapis.com/kubernetes-release/release}"
+
+    # Use the script from inside the Kubernetes tarball to fetch the client and
+    # server binaries (if not included in kubernetes.tar.gz).
+    function download_kube_binaries {
+      (
+        cd kubernetes
+        if [[ -x ./cluster/get-kube-binaries.sh ]]; then
+          ./cluster/get-kube-binaries.sh
+        fi
+      )
+    }
+
     function create_cluster {
+      if [[ -n "${KUBERNETES_SKIP_CREATE_CLUSTER-}" ]]; then
+        exit 0
+      fi
       echo "Creating a kubernetes on ${KUBERNETES_PROVIDER:-gce}..."
       (
         cd kubernetes
@@ -64,9 +101,21 @@ data:
       )
     }
 
-    if [[ "${KUBERNETES_SKIP_DOWNLOAD-}" ]]; then
+    if [[ -n "${KUBERNETES_SKIP_DOWNLOAD-}" ]]; then
       create_cluster
       exit 0
+    fi
+
+    if [[ -d "./kubernetes" ]]; then
+      if [[ -z "${KUBERNETES_SKIP_CONFIRM-}" ]]; then
+        echo "'kubernetes' directory already exist. Should we skip download step and start to create cluster based on it? [Y]/n"
+        read confirm
+        if [[ ! "${confirm}" =~ ^[nN]$ ]]; then
+          echo "Skipping download step."
+          create_cluster
+          exit 0
+        fi
+      fi
     fi
 
     function get_latest_version_number {
@@ -76,56 +125,71 @@ data:
       elif [[ $(which curl) ]]; then
         curl -Ss ${latest_url}
       else
-        echo "Couldn't find curl or wget.  Bailing out."
+        echo "Couldn't find curl or wget.  Bailing out." >&2
         exit 4
       fi
     }
 
-    release=$(get_latest_version_number)
-    release_url=https://storage.googleapis.com/kubernetes-release/release/${release}/kubernetes.tar.gz
+    release=${KUBERNETES_RELEASE:-$(get_latest_version_number)}
+    release_url="${KUBERNETES_RELEASE_URL}/${release}/kubernetes.tar.gz"
 
-    uname=$(uname)
-    if [[ "${uname}" == "Darwin" ]]; then
-      platform="darwin"
-    elif [[ "${uname}" == "Linux" ]]; then
-      platform="linux"
-    else
-      echo "Unknown, unsupported platform: (${uname})."
-      echo "Supported platforms: Linux, Darwin."
-      echo "Bailing out."
-      exit 2
-    fi
+    # TODO: remove client checks once kubernetes.tar.gz no longer includes client
+    # binaries by default.
+    kernel=$(uname -s)
+    case "${kernel}" in
+      Darwin)
+        platform="darwin"
+        ;;
+      Linux)
+        platform="linux"
+        ;;
+      *)
+        echo "Unknown, unsupported platform: ${kernel}." >&2
+        echo "Supported platforms: Linux, Darwin." >&2
+        echo "Bailing out." >&2
+        exit 2
+    esac
 
     machine=$(uname -m)
-    if [[ "${machine}" == "x86_64" ]]; then
-      arch="amd64"
-    elif [[ "${machine}" == "i686" ]]; then
-      arch="386"
-    elif [[ "${machine}" == "arm*" ]]; then
-      arch="arm"
-    else
-      echo "Unknown, unsupported architecture (${machine})."
-      echo "Supported architectures x86_64, i686, arm*"
-      echo "Bailing out."
-      exit 3
-    fi
+    case "${machine}" in
+      x86_64*|i?86_64*|amd64*)
+        arch="amd64"
+        ;;
+      aarch64*|arm64*)
+        arch="arm64"
+        ;;
+      arm*)
+        arch="arm"
+        ;;
+      i?86*)
+        arch="386"
+        ;;
+      *)
+        echo "Unknown, unsupported architecture (${machine})." >&2
+        echo "Supported architectures x86_64, i686, arm, arm64." >&2
+        echo "Bailing out." >&2
+        exit 3
+        ;;
+    esac
 
     file=kubernetes.tar.gz
 
-    echo "Downloading kubernetes release ${release} to ${PWD}/kubernetes.tar.gz"
-    if [[ -n "${KUBERNETES_SKIP_CONFIRM-}" ]]; then
+    echo "Downloading kubernetes release ${release}"
+    echo "  from ${release_url}"
+    echo "  to ${PWD}/kubernetes.tar.gz"
+    if [[ -z "${KUBERNETES_SKIP_CONFIRM-}" ]]; then
       echo "Is this ok? [Y]/n"
       read confirm
-      if [[ "$confirm" == "n" ]]; then
+      if [[ "${confirm}" =~ ^[nN]$ ]]; then
         echo "Aborting."
         exit 0
       fi
     fi
 
-    if [[ $(which wget) ]]; then
-      wget -O ${file} ${release_url}
-    elif [[ $(which curl) ]]; then
-      curl -L -o ${file} ${release_url}
+    if [[ $(which curl) ]]; then
+      curl -L -z ${file} ${release_url} -o ${file}
+    elif [[ $(which wget) ]]; then
+      wget -N ${release_url}
     else
       echo "Couldn't find curl or wget.  Bailing out."
       exit 1
@@ -133,8 +197,8 @@ data:
 
     echo "Unpacking kubernetes release ${release}"
     tar -xzf ${file}
-    rm ${file}
 
+    download_kube_binaries
     create_cluster
   get-kube-insecure.sh: |
     #!/bin/bash
